### ISSUE TITLE
add option to use secure websocket connection

### ISSUE THREAD

**Issue by phirestalker** [sergystepanov/webrtc-troubleshooting#5]
I was wondering if you could add the option to use secure websockets (wss). When I use this to test my traefik reverse proxy with webrtc I get the error.

`err: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.`

**Comment by sergystepanov** [comment]
Does it work now?

**Comment by phirestalker** [comment]
It is able to connect to websocket now.
